# Generated by Django 5.1 on 2024-08-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/<django.db.models.fields.related.OneToOneField>'),
        ),
    ]
