# Generated by Django 5.0.6 on 2024-08-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_task_options_task_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_on'], 'verbose_name': 'task'},
        ),
    ]
